all: h1 h2 h3 h4 h5 h6 h7 h8

clean:
	rm -f h1 h2 h3 h4 h5 h6 h7

h1: h1.c
	gcc -o h1 h1.c -Wall

h2: h2.c
	gcc -o h2 h2.c -Wall

h3: h3.c
	gcc -o h3 h3.c -Wall

h4: h4.c
	gcc -o h4 h4.c -Wall

h5: h5.c
	gcc -o h5 h5.c -Wall

h6: h6.c
	gcc -o h6 h6.c -Wall

h7: h7.c
	gcc -o h7 h7.c -Wall

h8: h8.c
	gcc -o h8 h8.c -Wall



